services:
  nginx:
    build: .
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      # Nginx logs
      - ./nginx/logs:/var/log/nginx
    networks:
      - web

networks:
  web:
    name: portfolio-web
